# .gitlab-ci.yml

# Define the stages of the pipeline
stages:
  - build
  - test

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Define individual jobs for the pipeline
# Each job belongs to a specific stage and executes a set of scripts
build:
  stage: build
  script:
    - pip install -r requirements.txt  # Install project dependencies listed in requirements.txt
    - python manage.py migrate  # Run database migrations

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Install project dependencies listed in requirements.txt
    - python manage.py test  # Run Django tests
