# Define the stages of the pipeline
stages:
  - build

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Define scripts to be executed before each job
before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend
