# Define stages for the pipeline
stages:
  - test
  - deploy

# Define job templates
.default_template: &default_template
  image: python:3.12.2  # Use Python 3.12.2 image
  services:
    - name: postgres:latest  # Use latest PostgreSQL image as a service
      alias: postgres
  before_script:
    - pip install -r requirements.txt  # Install Python dependencies
    - psql -h postgres -U postgres -c "CREATE DATABASE $POSTGRES_DB;"  # Create PostgreSQL database
  script:
    - python manage.py test  # Run Django tests

# Define jobs for each stage
test:
  stage: test
  <<: *default_template

deploy:
  stage: deploy
  script:
    - echo "Deployment steps here..."  # Add deployment steps here
  only:
    - backend  # Only deploy from the master branch
