stages:
  - lint
  - build
  - test

variables:
  POSTGRES_DB: your_db_name
  POSTGRES_USER: user
  POSTGRES_PASSWORD: secure_password

services:
  - postgres:latest

before_script:
  - apt-get update -y && apt-get install -y python3-pip python3-dev
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  script:
    - python manage.py test
  only:
    - backend