
stages:
  - build
  - test

variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

services:
  - name: postgres:latest
    alias: postgres

before_script:
  - apt-get update -y && apt-get install -y python3-pip python3-dev
  - pip3 install virtualenv

build:
  stage: build
  tags:
    - postgres  
  script:
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  tags:
    - postgres  
  script:
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py test
  only:
    - backend
