# .gitlab-ci.yml

# Définir les étapes du pipeline
stages:
  - build
  - test

# Définir les variables globales pour la configuration de PostgreSQL
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Définir les travaux individuels pour le pipeline
# Chaque travail appartient à une étape spécifique et exécute un ensemble de scripts
build:
  stage: build
  script:
    - pip install -r C:\Users\fguent\cft\requirements.txt   # Installer les dépendances du projet répertoriées dans requirements.txt
    - python manage.py migrate  # Exécuter les migrations de base de données
  only:
    - backend 
test:
  stage: test
  script:
    - pip install -r C:\Users\fguent\cft\requirements.txt  # Installer les dépendances du projet répertoriées dans requirements.txt
    - python manage.py test  # Exécuter les tests Django
  only:
    - backend