# .gitlab-ci.yml

# Define the stages of the pipeline
stages:
  - build
  - test

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Define services used by the pipeline
services:
  - name: postgres:latest
    alias: postgres

# Define scripts to be executed before each job
before_script:
  # Install Python dependencies and set up virtual environment
  - python -m venv venv
  - venv\Scripts\activate
  - pip install -r requirements.txt

# Define individual jobs for the pipeline
# Each job belongs to a specific stage and executes a set of scripts
build:
  stage: build
  script:
    - python manage.py migrate
    # Add additional build steps if needed
  only:
    - backend

test:
  stage: test
  script:
    - python manage.py test
    # Add additional test steps if needed
  only:
    - backend 
