# Define the stages of the pipeline
stages:
  - build
  - test

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

services:
  - postgres:latest

# Install Python and required packages
before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install virtualenv

# Define individual jobs for the pipeline
# Each job belongs to a specific stage and executes a set of scripts
build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  script:
    - source venv/bin/activate
    - python manage.py test
  only:
    - backend
