# Define stages for the pipeline
stages:
  - build

# Define job templates
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

build:
  stage: build
  image: python:3.12.2
  script:
    - python manage.py migrate
  only:
    - backend
