# Define the stages of the pipeline
stages:
  - build
  - test

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Define services used by the pipeline
services:
  - name: postgres:latest

# Define scripts to be executed before each job
before_script:
  - apk add --no-cache python3 py3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

# Define individual jobs for the pipeline
# Each job belongs to a specific stage and executes a set of scripts
build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  script:
    - python manage.py test
  only:
    - backend
