# Define stages for the pipeline
stages:
  - build
  - test

# Define job templates
.default_template: &default_template
  image: python:3.12.2  # Use Python 3.12.2 image
  services:
    - name: postgres:latest  # Use latest PostgreSQL image as a service
      alias: postgres
  before_script:
    - pip install -r requirements.txt  # Install Python dependencies
    - psql -h postgres -U postgres -c "CREATE DATABASE $POSTGRES_DB;"  # Create PostgreSQL database
  script:
    - python manage.py test  # Run Django tests

build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - main

test:
  stage: test
  script:
    - python manage.py test
  only:
    - main