stages:
  - build

# Define job templates
.default_template: &default_template
  image: python:3.12.2-alpine  # Use Python 3.12.2 on Alpine Linux
  services:
    - name: postgres:latest  # Use latest PostgreSQL image as a service
      alias: postgres
      environment:
        POSTGRES_DB: "CFTdatabase"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "SopraHR2024++"
  before_script:
    - pip install --default-timeout=600 --retries=5 -r requirements.txt  # Install Python dependencies with retry and timeout options
    - python manage.py migrate

build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend

