# Define stages for the pipeline
stages:
  - build

# Define job templates
.default_template: &default_template
  image: python:3.12.2-alpine  # Use Python 3.12.2 on Alpine Linux
  services:
    - name: postgres:latest  # Use latest PostgreSQL image as a service
      alias: postgres
      environment:
        POSTGRES_DB: "CFTdatabase"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "SopraHR2024++"
  before_script:
    - apk update && apk add --no-cache postgresql-dev gcc python3-dev musl-dev  # Install PostgreSQL dependencies
    - python -m pip install --upgrade pip  # Upgrade pip
    - python -m pip install -r requirements.txt  # Install Python dependencies
    - python manage.py migrate  # Apply database migrations

build:
  <<: *default_template
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend
