# .gitlab-ci.yml

# Définir les étapes du pipeline
stages:
  - build
  - test

# Variables globales pour la configuration de PostgreSQL
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

# Scripts à exécuter avant chaque job
before_script:
 - pip install virtualenv  # Install virtualenv for creating isolated Python environments
 - virtualenv venv  # Create a virtual environment named "venv"
- source venv/bin/activate  # Activate the virtual environment

# Définir les jobs individuels pour le pipeline
# Chaque job appartient à une étape spécifique et exécute un ensemble de scripts
build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  script:
    - python manage.py test
  only:
    - backend