# Define the stages of the pipeline
stages:
  - build
  - test

# Define global variables for PostgreSQL configuration
variables:
  POSTGRES_DB: "CFTdatabase"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SopraHR2024++"

services:
  - postgres:latest

before_script:
  - python -m venv venv
  - venv\Scripts\activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  script:
    - python manage.py test
  only:
    - backend