# Define stages for the pipeline
stages:
  - build
  - test

# Define job templates
.default_template: &default_template
  image: python:3.12.2  # Utiliser l'image Python 3.12.2
  services:
    - name: postgres:latest  # Utiliser l'image PostgreSQL la plus récente en tant que service
      alias: postgres
  before_script:
    - pip install -r requirements.txt  # Installer les dépendances Python
    - psql -h postgres -U postgres -c "CREATE DATABASE $POSTGRES_DB;"  # Créer la base de données PostgreSQL
  script:
    - python manage.py test  # Exécuter les tests Django

build:
  stage: build
  <<: *default_template
  script:
    - python manage.py migrate
  only:
    - backend

test:
  stage: test
  <<: *default_template
  script:
    - python manage.py test
  only:
    - backend
