# Generated by Django 5.0.3 on 2024-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
